<?php
/**
 * Tiago Sampaio
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  TS
 * @package   TS_ApiPlus
 *
 * @copyright Copyright (c) 2016 Tiago Sampaio. (http://tiagosampaio.com)
 * @license   https://opensource.org/licenses/MIT The MIT License
 *
 * @author    Tiago Sampaio <tiago@tiagosampaio.com>
 */
trait TS_ApiPlus_Trait_Http
{

    /**
     * @param int  $code
     * @param null $message
     *
     * @return void
     *
     * @throws Zend_Controller_Response_Exception
     */
    protected function sendHttpSuccessResponse($code, $message = null, $additionalData = array())
    {
        $data = array(
            'error'   => false,
            'message' => $message
        );

        if (!empty($additionalData) && is_array($additionalData)) {
            foreach ((array) $additionalData as $key => $value) {
                $data[$key] = $value;
            }
        }

        $this->sendHttpResponse($code, $data);
    }

    /**
     * @param int  $code
     * @param null $message
     *
     * @return void
     *
     * @throws Zend_Controller_Response_Exception
     */
    protected function sendHttpErrorResponse($code, $message = null, $additionalData = array())
    {
        $data = array(
            'error'   => true,
            'message' => $message
        );

        if (!empty($additionalData) && is_array($additionalData)) {
            foreach ((array) $additionalData as $key => $value) {
                $data[$key] = $value;
            }
        }

        $this->sendHttpResponse($code, $data);
    }


    /**
     * @param string $code
     * @param array  $data
     *
     * @throws Zend_Controller_Response_Exception
     */
    protected function sendHttpResponse($code, $data = array())
    {
        $this->getHttpResponse()->setHttpResponseCode($code);
        $this->getHttpResponse()->setBody(Zend_Json_Encoder::encode($data));
        $this->getHttpResponse()->sendResponse();

        die();
    }


    /**
     * @return Mage_Core_Controller_Response_Http
     */
    protected function getHttpResponse()
    {
        return Mage::app()->getResponse();
    }


    /**
     * @return Mage_Core_Controller_Request_Http
     */
    protected function getHttpRequest()
    {
        return Mage::app()->getRequest();
    }

}
