<?php
/**
 * Tiago Sampaio
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  TS
 * @package   TS_SimpleApi
 *
 * @copyright Copyright (c) 2016 Tiago Sampaio. (http://tiagosampaio.com)
 *
 * @author    Tiago Sampaio <tiago@tiagosampaio.com>
 */
class TS_SimpleApi_SimpleController extends TS_SimpleApi_Controller_Front_Action
{

    public function indexAction()
    {
        $username = $this->getRequest()->getHeader('apiUsername');
        $apiKey   = $this->getRequest()->getHeader('apiKey');

        /** @var Mage_Api_Model_User $user */
        $user = Mage::getModel('api/user');

        if (false == $user->authenticate($username, $apiKey)) {
            $this->getResponse()->setHttpResponseCode(401);
            $this->getResponse()->sendHeadersAndExit();

            return;
        }

        /** @var Mage_Api_Model_Session $session */
        $session = Mage::getSingleton('api/session');
        $session->login($username, $apiKey);

        $resource = $this->getRequest()->getPost('resource', null);
        $args     = $this->getRequest()->getPost('args', array());

        if (empty($resource)) {
            $this->getResponse()->setHttpResponseCode(401);
            $this->getResponse()->sendHeadersAndExit();
        }

        try {
            /** @var TS_SimpleApi_Model_Server_Handler $handler */
            $handler = Mage::getModel('ts_simpleapi/server_handler');
            $result  = $handler->callSimple($resource, $args);

            $this->getResponse()->setHeader('Content-type', 'application/json', true);
            $this->getResponse()->setBody(Zend_Json_Encoder::encode($result));
        } catch (Exception $e) {

        }
    }

}
