<?php
/**
 * Tiago Sampaio
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  TS
 * @package   TS_SimpleApi
 *
 * @copyright Copyright (c) 2016 Tiago Sampaio. (http://tiagosampaio.com)
 *
 * @author    Tiago Sampaio <tiago@tiagosampaio.com>
 */
class TS_ApiPlus_JsonController extends TS_ApiPlus_Controller_Front_Action
{

    public function callAction()
    {
        $username = $this->getRequest()->getHeader('apiUsername');
        $apiKey   = $this->getRequest()->getHeader('apiKey');

        /** @var Mage_Api_Model_User $user */
        $user = Mage::getModel('api/user');

        if (false == $user->authenticate($username, $apiKey)) {
            $this->sendHttpResponse(TS_ApiPlus_Model_Http_Response::HTTP_UNAUTHORIZED);
        }

        /** @var Mage_Api_Model_Session $session */
        $session = Mage::getSingleton('api/session');
        $session->login($username, $apiKey);

        /** @var string $request */
        $request = file_get_contents('php://input');

        /** @var stdClass $json */
        $json     = Zend_Json_Decoder::decode($request, Zend_Json::TYPE_OBJECT);
        $resource = (string) $json->resource;
        $args     = $json->args ?: null;

        if (empty($resource)) {
            $this->sendHttpResponse(TS_ApiPlus_Model_Http_Response::HTTP_METHOD_NOT_ALLOWED);
        }

        try {
            /** @var TS_ApiPlus_Model_Server_Handler $handler */
            $handler = Mage::getModel('ts_apiplus/server_handler');
            $result  = $handler->callSimple($resource, $args);

            $this->getResponse()->setHeader('Content-type', 'application/json', true);
            $this->getResponse()->setBody(Zend_Json_Encoder::encode($result));
        } catch (Exception $e) {
            $this->sendHttpResponse(TS_ApiPlus_Model_Http_Response::HTTP_INTERNAL_SERVER_ERROR);
        }
    }

}
