<?php
/**
 * Tiago Sampaio
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  TS
 * @package   TS_SimpleApi
 *
 * @copyright Copyright (c) 2016 Tiago Sampaio. (http://tiagosampaio.com)
 *
 * @author    Tiago Sampaio <tiago@tiagosampaio.com>
 */
class TS_ApiPlus_JsonController extends TS_ApiPlus_Controller_Front_Action
{

    public function indexAction()
    {
        $this->getApiRequest()->dispatch();
    }

}
