<?php
/**
 * Tiago Sampaio
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  TS
 * @package   TS_SimpleApi
 *
 * @copyright Copyright (c) 2016 Tiago Sampaio. (http://tiagosampaio.com)
 *
 * @author    Tiago Sampaio <tiago@tiagosampaio.com>
 */
trait TS_SimpleApi_Trait_Data
{

    use TS_SimpleApi_Trait_Config;


    /**
     * Get the common helper.
     *
     * @return TS_SimpleApi_Helper_Data
     */
    protected function helper()
    {
        return Mage::helper('ts_simpleapi');
    }

}
