<?php
/**
 * Tiago Sampaio
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  TS
 * @package   TS_ApiPlus
 *
 * @copyright Copyright (c) 2016 Tiago Sampaio. (http://tiagosampaio.com)
 *
 * @author    Tiago Sampaio <tiago@tiagosampaio.com>
 */
class TS_ApiPlus_Controller_Front_Action extends Mage_Core_Controller_Front_Action
{

    use TS_ApiPlus_Trait_Data;


    public function preDispatch()
    {
        parent::preDispatch();
    }

}
