<?php
/**
 * Tiago Sampaio
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  TS
 * @package   TS_ApiPlus
 *
 * @copyright Copyright (c) 2016 Tiago Sampaio. (http://tiagosampaio.com)
 *
 * @author    Tiago Sampaio <tiago@tiagosampaio.com>
 */
class TS_ApiPlus_Controller_Front_Action extends Mage_Core_Controller_Front_Action
{

    use TS_ApiPlus_Trait_Data;


    /**
     * @param int  $code
     * @param null $message
     *
     * @return void
     *
     * @throws Zend_Controller_Response_Exception
     */
    protected function sendHttpResponse($code, $message = null)
    {
        $this->getResponse()->setHttpResponseCode($code);
        $this->getResponse()->setBody(Zend_Json_Encoder::encode(array('result' => $message)));
        $this->getResponse()->sendHeadersAndExit();
    }

}
